---
- name: Create instance
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    service_account_email: ansible-service-account@ansible-cloud-jwade005.iam.gserviceaccount.com
    credentials_file: /Users/Jonathan/Desktop/nti460/ansible-cloud-jwade005-eabb0ad817f3.json
    project_id: ansible-cloud-jwade005
    machine_type: f1-micro
    image: centos-7

  tasks:

   - name: Launch instances
     gce:
         instance_names: dev
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
         service_account_email: "{{ service_account_email }}"
         credentials_file: "{{ credentials_file }}"
         project_id: "{{ project_id }}"
