---
  - name: Transfer and execute a script.
    hosts: webserver
    user: ec2-user
    sudo: yes
    tasks:
      - name: Transfer the script
        copy: src=/home/ec2-user/NTI-310/Apache/apache-install.sh dest=/home/ec2-user mode=0777

      - name: Execute the script
        command: sh /home/ec2-user/apache-install.sh
